### ISSUE TITLE
Making input yaml-file compliant to python-syntax

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/data-validator#10]
To facilitate the pyyaml-usage, the syntax should be in agreement to general python dtypes; actually lists as currently used:

``` YAML
numberRange: [0.5,1] # correct syntax
numberRange: [,200]  # incorrect syntax
numberRange: [1,]    # correct syntax
numberRange: [,]     # Incorrect syntax
```

Using the currently proposed syntax for min/max values only is not in correspondence, possible alternatives:
- using the key-words min and max 

``` YAML
numberRange: [0.5,1] 
numberMax: 200  
numberMin: 1   
```
- using None (or other keyword) when min or max is of no importance:

``` YAML
numberRange: [0.5,1] 
numberRange: [None, 200]
numberRange: [1, None]
```
