### ISSUE TITLE
Multiple if statements linked with a single term

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/data-validator#17]
When reading in a YAML-file into a dictionary, non-unique key-values (i.e. using the same validation test twice), will not be interpreted into a dictionary and only one if-statement will be kept. For example:

``` yaml
            lifestage:
                if:
                    age:
                        min: 20
                        type: integer
                    allowed: [adult]
                if:
                    age:
                        max: 20
                        type: integer
                    allowed: [juvenile]
            age:
                type: integer
```

Loading the yaml string, will result in the following dictionary:

``` python
{'age': {'type': 'integer'},
 'lifestage': {'if': {'age': {'max': 20, 'type': 'integer'},
   'allowed': ['juvenile']}}}
```

Since key values should be unique in dictionaries, this will result in neglecting the first `if` validation.

Question is how we could adapt the setup of the YAML file to overcome this issue. Combining multiple ifs by using a list (enumeration `-`) is the preferred option, but probably be harder for the user to setup the yaml file:

``` yaml
lifestage:
    if:
        - age:
              min: 20
              type: integer
          allowed: [adult]
        - age:
              max: 20
              type: integer
          allowed: [juvenile]
age:
    type: integer
```

results in 

``` python
{'age': {'type': 'integer'},
 'lifestage': {'if': [{'age': {'min': 20, 'type': 'integer'},
    'allowed': ['adult']},
   {'age': {'max': 20, 'type': 'integer'}, 'allowed': ['juvenile']}]}}
```

would this be an appropriate solution?

@peterdesmet
